services:
  - type: web
    name: shadow-irc-app
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TCP_PORT
        value: 6667
